export const CHECKLIST_TABS = [
  { id: 'publication', label: 'Publication Order' },
  { id: 'planet', label: 'By Planet' },
  { id: 'eirik', label: "Eirik's Order" },
]

export const PLANET_ORDER = [
  'Canticle',
  'First of the Sun',
  'Komashi',
  'Lumar',
  'Nalthis',
  'Roshar',
  'Scadrial',
  'Sel',
  'Taldain',
  'Threnody',
]

export const COSMERE_WORKS = [
  {
    id: 'elantris',
    title: 'Elantris',
    type: 'Novel',
    planet: 'Sel',
    publicationOrder: 1,
    eirikOrder: 7,
    durationLabel: '~13.5 hours',
  },
  {
    id: 'the-hope-of-elantris',
    title: 'The Hope of Elantris',
    type: 'Short Story',
    planet: 'Sel',
    publicationOrder: 2,
    eirikOrder: 8,
    durationLabel: '~0.5 hours',
  },
  {
    id: 'mistborn-final-empire',
    title: 'Mistborn: The Final Empire',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 3,
    eirikOrder: 1,
    durationLabel: '~14.5 hours',
  },
  {
    id: 'mistborn-well-of-ascension',
    title: 'Mistborn: The Well of Ascension',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 4,
    eirikOrder: 2,
    durationLabel: '~16.5 hours',
  },
  {
    id: 'mistborn-hero-of-ages',
    title: 'Mistborn: The Hero of Ages',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 5,
    eirikOrder: 3,
    durationLabel: '~15.5 hours',
  },
  {
    id: 'warbreaker',
    title: 'Warbreaker',
    type: 'Novel',
    planet: 'Nalthis',
    publicationOrder: 6,
    eirikOrder: 6,
    durationLabel: '~13.5 hours',
  },
  {
    id: 'stormlight-way-of-kings',
    title: 'The Stormlight Archive: The Way of Kings',
    type: 'Novel',
    planet: 'Roshar',
    publicationOrder: 7,
    eirikOrder: 11,
    durationLabel: '~25.5 hours',
  },
  {
    id: 'mistborn-alloy-of-law',
    title: 'Mistborn: The Alloy of Law',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 8,
    eirikOrder: 18,
    durationLabel: '~6.5 hours',
  },
  {
    id: 'the-eleventh-metal',
    title: 'The Eleventh Metal',
    type: 'Short Story',
    planet: 'Scadrial',
    publicationOrder: 9,
    eirikOrder: 4,
    durationLabel: '~1 hour',
  },
  {
    id: 'emperors-soul',
    title: "The Emperor's Soul",
    type: 'Novella',
    planet: 'Sel',
    publicationOrder: 10,
    eirikOrder: 9,
    durationLabel: '~2 hours',
  },
  {
    id: 'shadows-for-silence',
    title: 'Shadows for Silence in the Forests of Hell',
    type: 'Novella',
    planet: 'Threnody',
    publicationOrder: 11,
    eirikOrder: 23,
    durationLabel: '~1.5 hours',
  },
  {
    id: 'stormlight-words-of-radiance',
    title: 'The Stormlight Archive: Words of Radiance',
    type: 'Novel',
    planet: 'Roshar',
    publicationOrder: 12,
    eirikOrder: 12,
    durationLabel: '~26.5 hours',
  },
  {
    id: 'sixth-of-the-dusk',
    title: 'Sixth of the Dusk',
    type: 'Novella',
    planet: 'First of the Sun',
    publicationOrder: 13,
    eirikOrder: 24,
    durationLabel: '~1.5 hours',
  },
  {
    id: 'allomancer-jak',
    title: 'Allomancer Jak and the Pits of Eltania',
    type: 'Short Story',
    planet: 'Scadrial',
    publicationOrder: 14,
    eirikOrder: 19,
    durationLabel: '~1.5 hours',
  },
  {
    id: 'mistborn-shadows-of-self',
    title: 'Mistborn: Shadows of Self',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 15,
    eirikOrder: 20,
    durationLabel: '~7.5 hours',
  },
  {
    id: 'mistborn-bands-of-mourning',
    title: 'Mistborn: The Bands of Mourning',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 16,
    eirikOrder: 21,
    durationLabel: '~8.5 hours',
  },
  {
    id: 'mistborn-secret-history',
    title: 'Mistborn: Secret History',
    type: 'Novella',
    planet: 'Scadrial',
    publicationOrder: 17,
    eirikOrder: 5,
    durationLabel: '~3.5 hours',
  },
  {
    id: 'stormlight-edgedancer',
    title: 'The Stormlight Archive: Edgedancer',
    type: 'Novella',
    planet: 'Roshar',
    publicationOrder: 18,
    eirikOrder: 13,
    durationLabel: '~2.5 hours',
  },
  {
    id: 'stormlight-oathbringer',
    title: 'The Stormlight Archive: Oathbringer',
    type: 'Novel',
    planet: 'Roshar',
    publicationOrder: 19,
    eirikOrder: 14,
    durationLabel: '~30.5 hours',
  },
  {
    id: 'stormlight-dawnshard',
    title: 'The Stormlight Archive: Dawnshard',
    type: 'Novella',
    planet: 'Roshar',
    publicationOrder: 20,
    eirikOrder: 15,
    durationLabel: '~3.5 hours',
  },
  {
    id: 'stormlight-rhythm-of-war',
    title: 'The Stormlight Archive: Rhythm of War',
    type: 'Novel',
    planet: 'Roshar',
    publicationOrder: 21,
    eirikOrder: 16,
    durationLabel: '~30.5 hours',
  },
  {
    id: 'mistborn-lost-metal',
    title: 'Mistborn: The Lost Metal',
    type: 'Novel',
    planet: 'Scadrial',
    publicationOrder: 22,
    eirikOrder: 22,
    durationLabel: '~10 hours',
  },
  {
    id: 'white-sand-omnibus',
    title: 'White Sand Omnibus',
    type: 'Graphic Novel',
    planet: 'Taldain',
    publicationOrder: 23,
    eirikOrder: 10,
    durationLabel: '~5 hours',
  },
  {
    id: 'tress',
    title: 'Tress of the Emerald Sea',
    type: 'Novel',
    planet: 'Lumar',
    publicationOrder: 24,
    eirikOrder: 26,
    durationLabel: '~7.5 hours',
  },
  {
    id: 'yumi',
    title: 'Yumi and the Nightmare Painter',
    type: 'Novel',
    planet: 'Komashi',
    publicationOrder: 25,
    eirikOrder: 27,
    durationLabel: '~9 hours',
  },
  {
    id: 'sunlit-man',
    title: 'The Sunlit Man',
    type: 'Novel',
    planet: 'Canticle',
    publicationOrder: 26,
    eirikOrder: 25,
    durationLabel: '~7.5 hours',
  },
  {
    id: 'stormlight-wind-and-truth',
    title: 'The Stormlight Archive: Wind and Truth',
    type: 'Novel',
    planet: 'Roshar',
    publicationOrder: 27,
    eirikOrder: 17,
    durationLabel: '~33 hours',
  },
  {
    id: 'isles-of-the-emberdark',
    title: 'Isles of the Emberdark',
    type: 'Novel',
    planet: 'First of the Sun',
    publicationOrder: 28,
    eirikOrder: 28,
    durationLabel: '~8 hours',
  },
]
